/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis.logins;

import authenticate.IConnectable;
import guis.applicCapitainerie.ApplicCapitainerie;
import authenticate.VerificateurUsersPasswordHash;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Jija
 */
public class DialLogin extends java.awt.Dialog implements ActionListener {
    public VerificateurUsersPasswordHash vuph;
    private boolean logged;

    public void setLogged(boolean logged) {
        this.logged = logged;
    }

    public boolean isLogged() {
        return logged;
    }
    /**
     * Creates new form DialLogin
     */
    public DialLogin(IConnectable parent, boolean modal) {
        super((java.awt.Frame)parent, modal);
        initComponents();
        
        this.logged = false;
        this.buttonOk.addActionListener(this);
        this.buttonChange.addActionListener(this);
        this.buttonCancel.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        textFieldLogin = new java.awt.TextField();
        label2 = new java.awt.Label();
        textFieldPwd = new java.awt.TextField();
        label3 = new java.awt.Label();
        buttonChange = new java.awt.Button();
        buttonOk = new java.awt.Button();
        buttonCancel = new java.awt.Button();

        setLocationRelativeTo(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new java.awt.GridLayout(4, 2));

        label1.setText("User:");
        add(label1);
        add(textFieldLogin);

        label2.setText("Password:");
        add(label2);
        add(textFieldPwd);

        label3.setText("Change password ? ==>");
        add(label3);

        buttonChange.setEnabled(false);
        buttonChange.setLabel("Change");
        add(buttonChange);

        buttonOk.setLabel("Ok");
        add(buttonOk);

        buttonCancel.setLabel("Cancel");
        add(buttonCancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialLogin dialog = new DialLogin(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonCancel;
    private java.awt.Button buttonChange;
    private java.awt.Button buttonOk;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField textFieldLogin;
    private java.awt.TextField textFieldPwd;
    // End of variables declaration//GEN-END:variables

    public void clear()
    {
        textFieldLogin.setText("");
        textFieldPwd.setText("");
        
        buttonChange.setEnabled(false);
        textFieldLogin.setEnabled(true);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == this.buttonOk){
            if (vuph == null)
                vuph = new VerificateurUsersPasswordHash(this.textFieldLogin.getText(), this.textFieldPwd.getText());
            
            vuph.setLogin(textFieldLogin.getText());
            vuph.setPwdIn(textFieldPwd.getText());
            
            if(vuph.isOk()){
                System.out.println("Connected");
                this.textFieldLogin.setEnabled(false);
                this.buttonChange.setEnabled(true);
                this.logged = true;
                if(this.getParent() != null)
                    ((IConnectable)this.getParent()).connection();
            }
            else
                javax.swing.JOptionPane.showMessageDialog(null, "Mauvais mot de passe");
        }
        
        else if(e.getSource() == this.buttonCancel){
            /*this.textFieldLogin.setText("");
            this.textFieldPwd.setText("");
            System.out.println("logged out");
            this.logged = false;*/
            this.setVisible(false);
        }
        
        else if(e.getSource() == this.buttonChange){
            if(this.logged){
                if(vuph.isValid(this.textFieldPwd.getText()))
                {
                    vuph.changePwd(this.textFieldLogin.getText(), this.textFieldPwd.getText());
                    vuph.setPwdIn(this.textFieldPwd.getText());
                }
                else
                    javax.swing.JOptionPane.showMessageDialog(null, "Mauvais mot de passe");
            }
            else
                System.out.println("NOT CONNECTED");
        }
    }
}
